name: Build & Push CI Image

on:
  push:
    paths:
      - "Dockerfile.ci"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: git.max-richter.dev
          username: ${{ gitea.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ci
          push: true
          tags: |
            git.max-richter.dev/${{ gitea.repository }}-ci:latest
            git.max-richter.dev/${{ gitea.repository }}-ci:${{ github.sha }}
